### ISSUE TITLE
Little note on the setup examples

### ISSUE THREAD

**Issue by Ciel-MC** [roobert/palette.nvim#1]
2 small things:
- Lazy says that you don't need to make themes lazy=false, because when you run the colorscheme command, it will work automagically.
- In the first lazy setup example, the project is missing the ".nvim" prefix

**Comment by roobert** [comment]
Thanks for pointing these out, I've corrected the README!

**Comment by Ciel-MC** [comment]
Forgot to mention, the new setup might not function as intended, since `config` is called when the plugin was asked for by some other mean, and when it is decided to be lazy loaded, and when it's lazy loaded, it wouldn't load itself anymore, if the desired behavior was to load on startup, maybe the call should be in `init` instead?

**Comment by roobert** [comment]
OK thanks, I've reverted the last change.

I did test removing `lazy=false` and saw no noticeable difference but I also think it does no harm and this is one of the first things that needs to be loaded anyway.
